#DEV evironment

app:
  message: This is the property file fo the ${spring.application.name} specefic to PROD Environment

spring:
  datesource:
    driver-class-name: com.msql.cj.jdbc.Driver
    url: <MYSQL_URL>
    username: <USERNAME>
    password: <PASSWORD>